package com.example.demo.entity;
// Generated 2019-1-8 8:52:12 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestUser generated by hbm2java
 */
@Entity
@Table(name = "TEST_USER", schema = "SCOTT")
public class TestUser implements java.io.Serializable {

	private Long id;
	private String userName;
	private String password;

	public TestUser() {
	}

	public TestUser(Long id) {
		this.id = id;
	}

	public TestUser(Long id, String userName, String password) {
		this.id = id;
		this.userName = userName;
		this.password = password;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "USER_NAME", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "TestUser [id=" + id + ", userName=" + userName + ", password=" + password + "]";
	}
	
}
