package org.ePDM_project.repository.entity;
// Generated 2019-1-11 11:26:35 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Phase generated by hbm2java
 */
@Entity
@Table(name = "PHASE", uniqueConstraints = { @UniqueConstraint(columnNames = "ENTITY_UID"),
		@UniqueConstraint(columnNames = "CODE") })
public class Phase implements java.io.Serializable {

	private Long id;
	private Project project;
	private String entityUid;
	private Long entityversion;
	private Long entitystate;
	private String eneitycreator;
	private String entitymodifier;
	private Serializable entitycreated;
	private Serializable entitymodified;
	private String pdmcreator;
	private String pdmmodifier;
	private String name;
	private String code;
	private String info;
	private String applierNo;
	private String applierName;
	private String applierEmail;
	private String applierPhone;
	private String applierDptno;
	private String applierDptname;
	private Serializable applyDate;
	private Blob objectbytes;
	private Long processInstanceId;
	private String businessState;
	private Long taskInstanceId;
	private String taskPriority;
	private Serializable scheduledStart;
	private Serializable scheduledComplete;
	private Serializable start;
	private Serializable end;
	private Long earlywarningdays;
	private String phaseType;
	private String formCode;
	private Serializable passDate;
	private String formKey;
	private String pdmCreatorPersonName;
	private String pdmModifierPersonName;
	private Serializable pdmModified;

	public Phase() {
	}

	public Phase(Long id, String entityUid) {
		this.id = id;
		this.entityUid = entityUid;
	}

	public Phase(Long id, Project project, String entityUid, Long entityversion, Long entitystate, String eneitycreator,
			String entitymodifier, Serializable entitycreated, Serializable entitymodified, String pdmcreator,
			String pdmmodifier, String name, String code, String info, String applierNo, String applierName,
			String applierEmail, String applierPhone, String applierDptno, String applierDptname,
			Serializable applyDate, Blob objectbytes, Long processInstanceId, String businessState, Long taskInstanceId,
			String taskPriority, Serializable scheduledStart, Serializable scheduledComplete, Serializable start,
			Serializable end, Long earlywarningdays, String phaseType, String formCode, Serializable passDate,
			String formKey, String pdmCreatorPersonName, String pdmModifierPersonName, Serializable pdmModified) {
		this.id = id;
		this.project = project;
		this.entityUid = entityUid;
		this.entityversion = entityversion;
		this.entitystate = entitystate;
		this.eneitycreator = eneitycreator;
		this.entitymodifier = entitymodifier;
		this.entitycreated = entitycreated;
		this.entitymodified = entitymodified;
		this.pdmcreator = pdmcreator;
		this.pdmmodifier = pdmmodifier;
		this.name = name;
		this.code = code;
		this.info = info;
		this.applierNo = applierNo;
		this.applierName = applierName;
		this.applierEmail = applierEmail;
		this.applierPhone = applierPhone;
		this.applierDptno = applierDptno;
		this.applierDptname = applierDptname;
		this.applyDate = applyDate;
		this.objectbytes = objectbytes;
		this.processInstanceId = processInstanceId;
		this.businessState = businessState;
		this.taskInstanceId = taskInstanceId;
		this.taskPriority = taskPriority;
		this.scheduledStart = scheduledStart;
		this.scheduledComplete = scheduledComplete;
		this.start = start;
		this.end = end;
		this.earlywarningdays = earlywarningdays;
		this.phaseType = phaseType;
		this.formCode = formCode;
		this.passDate = passDate;
		this.formKey = formKey;
		this.pdmCreatorPersonName = pdmCreatorPersonName;
		this.pdmModifierPersonName = pdmModifierPersonName;
		this.pdmModified = pdmModified;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "ENTITY_UID", unique = true, nullable = false, length = 72)
	public String getEntityUid() {
		return this.entityUid;
	}

	public void setEntityUid(String entityUid) {
		this.entityUid = entityUid;
	}

	@Column(name = "ENTITYVERSION", precision = 10, scale = 0)
	public Long getEntityversion() {
		return this.entityversion;
	}

	public void setEntityversion(Long entityversion) {
		this.entityversion = entityversion;
	}

	@Column(name = "ENTITYSTATE", precision = 10, scale = 0)
	public Long getEntitystate() {
		return this.entitystate;
	}

	public void setEntitystate(Long entitystate) {
		this.entitystate = entitystate;
	}

	@Column(name = "ENEITYCREATOR", length = 100)
	public String getEneitycreator() {
		return this.eneitycreator;
	}

	public void setEneitycreator(String eneitycreator) {
		this.eneitycreator = eneitycreator;
	}

	@Column(name = "ENTITYMODIFIER", length = 100)
	public String getEntitymodifier() {
		return this.entitymodifier;
	}

	public void setEntitymodifier(String entitymodifier) {
		this.entitymodifier = entitymodifier;
	}

	@Column(name = "ENTITYCREATED")
	public Serializable getEntitycreated() {
		return this.entitycreated;
	}

	public void setEntitycreated(Serializable entitycreated) {
		this.entitycreated = entitycreated;
	}

	@Column(name = "ENTITYMODIFIED")
	public Serializable getEntitymodified() {
		return this.entitymodified;
	}

	public void setEntitymodified(Serializable entitymodified) {
		this.entitymodified = entitymodified;
	}

	@Column(name = "PDMCREATOR", length = 510)
	public String getPdmcreator() {
		return this.pdmcreator;
	}

	public void setPdmcreator(String pdmcreator) {
		this.pdmcreator = pdmcreator;
	}

	@Column(name = "PDMMODIFIER", length = 510)
	public String getPdmmodifier() {
		return this.pdmmodifier;
	}

	public void setPdmmodifier(String pdmmodifier) {
		this.pdmmodifier = pdmmodifier;
	}

	@Column(name = "NAME", length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", unique = true, length = 510)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "INFO", length = 510)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "APPLIER_NO", length = 510)
	public String getApplierNo() {
		return this.applierNo;
	}

	public void setApplierNo(String applierNo) {
		this.applierNo = applierNo;
	}

	@Column(name = "APPLIER_NAME", length = 510)
	public String getApplierName() {
		return this.applierName;
	}

	public void setApplierName(String applierName) {
		this.applierName = applierName;
	}

	@Column(name = "APPLIER_EMAIL", length = 510)
	public String getApplierEmail() {
		return this.applierEmail;
	}

	public void setApplierEmail(String applierEmail) {
		this.applierEmail = applierEmail;
	}

	@Column(name = "APPLIER_PHONE", length = 510)
	public String getApplierPhone() {
		return this.applierPhone;
	}

	public void setApplierPhone(String applierPhone) {
		this.applierPhone = applierPhone;
	}

	@Column(name = "APPLIER_DPTNO", length = 510)
	public String getApplierDptno() {
		return this.applierDptno;
	}

	public void setApplierDptno(String applierDptno) {
		this.applierDptno = applierDptno;
	}

	@Column(name = "APPLIER_DPTNAME", length = 510)
	public String getApplierDptname() {
		return this.applierDptname;
	}

	public void setApplierDptname(String applierDptname) {
		this.applierDptname = applierDptname;
	}

	@Column(name = "APPLY_DATE")
	public Serializable getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Serializable applyDate) {
		this.applyDate = applyDate;
	}

	@Column(name = "OBJECTBYTES")
	public Blob getObjectbytes() {
		return this.objectbytes;
	}

	public void setObjectbytes(Blob objectbytes) {
		this.objectbytes = objectbytes;
	}

	@Column(name = "PROCESS_INSTANCE_ID", scale = 0)
	public Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	@Column(name = "BUSINESS_STATE", length = 510)
	public String getBusinessState() {
		return this.businessState;
	}

	public void setBusinessState(String businessState) {
		this.businessState = businessState;
	}

	@Column(name = "TASK_INSTANCE_ID", scale = 0)
	public Long getTaskInstanceId() {
		return this.taskInstanceId;
	}

	public void setTaskInstanceId(Long taskInstanceId) {
		this.taskInstanceId = taskInstanceId;
	}

	@Column(name = "TASK_PRIORITY", length = 510)
	public String getTaskPriority() {
		return this.taskPriority;
	}

	public void setTaskPriority(String taskPriority) {
		this.taskPriority = taskPriority;
	}

	@Column(name = "SCHEDULED_START")
	public Serializable getScheduledStart() {
		return this.scheduledStart;
	}

	public void setScheduledStart(Serializable scheduledStart) {
		this.scheduledStart = scheduledStart;
	}

	@Column(name = "SCHEDULED_COMPLETE")
	public Serializable getScheduledComplete() {
		return this.scheduledComplete;
	}

	public void setScheduledComplete(Serializable scheduledComplete) {
		this.scheduledComplete = scheduledComplete;
	}

	@Column(name = "START_")
	public Serializable getStart() {
		return this.start;
	}

	public void setStart(Serializable start) {
		this.start = start;
	}

	@Column(name = "END_")
	public Serializable getEnd() {
		return this.end;
	}

	public void setEnd(Serializable end) {
		this.end = end;
	}

	@Column(name = "EARLYWARNINGDAYS", precision = 10, scale = 0)
	public Long getEarlywarningdays() {
		return this.earlywarningdays;
	}

	public void setEarlywarningdays(Long earlywarningdays) {
		this.earlywarningdays = earlywarningdays;
	}

	@Column(name = "PHASE_TYPE", length = 510)
	public String getPhaseType() {
		return this.phaseType;
	}

	public void setPhaseType(String phaseType) {
		this.phaseType = phaseType;
	}

	@Column(name = "FORM_CODE", length = 510)
	public String getFormCode() {
		return this.formCode;
	}

	public void setFormCode(String formCode) {
		this.formCode = formCode;
	}

	@Column(name = "PASS_DATE")
	public Serializable getPassDate() {
		return this.passDate;
	}

	public void setPassDate(Serializable passDate) {
		this.passDate = passDate;
	}

	@Column(name = "FORM_KEY", length = 1020)
	public String getFormKey() {
		return this.formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}

	@Column(name = "PDM_CREATOR_PERSON_NAME", length = 1020)
	public String getPdmCreatorPersonName() {
		return this.pdmCreatorPersonName;
	}

	public void setPdmCreatorPersonName(String pdmCreatorPersonName) {
		this.pdmCreatorPersonName = pdmCreatorPersonName;
	}

	@Column(name = "PDM_MODIFIER_PERSON_NAME", length = 1020)
	public String getPdmModifierPersonName() {
		return this.pdmModifierPersonName;
	}

	public void setPdmModifierPersonName(String pdmModifierPersonName) {
		this.pdmModifierPersonName = pdmModifierPersonName;
	}

	@Column(name = "PDM_MODIFIED")
	public Serializable getPdmModified() {
		return this.pdmModified;
	}

	public void setPdmModified(Serializable pdmModified) {
		this.pdmModified = pdmModified;
	}

}
