package org.ePDM_project.repository.entity;
// Generated 2019-1-11 11:26:35 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "PROJECT", uniqueConstraints = { @UniqueConstraint(columnNames = "ENTITY_UID"),
		@UniqueConstraint(columnNames = "ORIGINAL_NAME"), @UniqueConstraint(columnNames = "NAME") })
public class Project implements java.io.Serializable {

	private Long id;
	private String entityUid;
	private Long entityversion;
	private Long entitystate;
	private String eneitycreator;
	private String entitymodifier;
	private Serializable entitycreated;
	private Serializable entitymodified;
	private String pdmcreator;
	private String pdmmodifier;
	private String name;
	private String code;
	private String info;
	private String applierNo;
	private String applierName;
	private String applierEmail;
	private String applierPhone;
	private String applierDptno;
	private String applierDptname;
	private Serializable applyDate;
	private Blob objectbytes;
	private Long processInstanceId;
	private String businessState;
	private Long taskInstanceId;
	private String taskPriority;
	private Serializable scheduledStart;
	private Serializable scheduledComplete;
	private Serializable start;
	private Serializable end;
	private String principalAccountName;
	private String principalPersonName;
	private String principalEmail;
	private String principalExtension;
	private String projecttype;
	private String delaystate;
	private Integer isdelay;
	private Long version;
	private Long flowChartVersion;
	private Long projectFormId;
	private Long pictureId;
	private String formCode;
	private String originalName;
	private String createyear;
	private Serializable passDate;
	private String formKey;
	private String pdmCreatorPersonName;
	private String pdmModifierPersonName;
	private Serializable pdmModified;
	private String othercode;
	private Set phases = new HashSet(0);

	public Project() {
	}

	public Project(Long id, String entityUid) {
		this.id = id;
		this.entityUid = entityUid;
	}

	public Project(Long id, String entityUid, Long entityversion, Long entitystate, String eneitycreator,
			String entitymodifier, Serializable entitycreated, Serializable entitymodified, String pdmcreator,
			String pdmmodifier, String name, String code, String info, String applierNo, String applierName,
			String applierEmail, String applierPhone, String applierDptno, String applierDptname,
			Serializable applyDate, Blob objectbytes, Long processInstanceId, String businessState, Long taskInstanceId,
			String taskPriority, Serializable scheduledStart, Serializable scheduledComplete, Serializable start,
			Serializable end, String principalAccountName, String principalPersonName, String principalEmail,
			String principalExtension, String projecttype, String delaystate, Integer isdelay, Long version,
			Long flowChartVersion, Long projectFormId, Long pictureId, String formCode, String originalName,
			String createyear, Serializable passDate, String formKey, String pdmCreatorPersonName,
			String pdmModifierPersonName, Serializable pdmModified, String othercode, Set phases) {
		this.id = id;
		this.entityUid = entityUid;
		this.entityversion = entityversion;
		this.entitystate = entitystate;
		this.eneitycreator = eneitycreator;
		this.entitymodifier = entitymodifier;
		this.entitycreated = entitycreated;
		this.entitymodified = entitymodified;
		this.pdmcreator = pdmcreator;
		this.pdmmodifier = pdmmodifier;
		this.name = name;
		this.code = code;
		this.info = info;
		this.applierNo = applierNo;
		this.applierName = applierName;
		this.applierEmail = applierEmail;
		this.applierPhone = applierPhone;
		this.applierDptno = applierDptno;
		this.applierDptname = applierDptname;
		this.applyDate = applyDate;
		this.objectbytes = objectbytes;
		this.processInstanceId = processInstanceId;
		this.businessState = businessState;
		this.taskInstanceId = taskInstanceId;
		this.taskPriority = taskPriority;
		this.scheduledStart = scheduledStart;
		this.scheduledComplete = scheduledComplete;
		this.start = start;
		this.end = end;
		this.principalAccountName = principalAccountName;
		this.principalPersonName = principalPersonName;
		this.principalEmail = principalEmail;
		this.principalExtension = principalExtension;
		this.projecttype = projecttype;
		this.delaystate = delaystate;
		this.isdelay = isdelay;
		this.version = version;
		this.flowChartVersion = flowChartVersion;
		this.projectFormId = projectFormId;
		this.pictureId = pictureId;
		this.formCode = formCode;
		this.originalName = originalName;
		this.createyear = createyear;
		this.passDate = passDate;
		this.formKey = formKey;
		this.pdmCreatorPersonName = pdmCreatorPersonName;
		this.pdmModifierPersonName = pdmModifierPersonName;
		this.pdmModified = pdmModified;
		this.othercode = othercode;
		this.phases = phases;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ENTITY_UID", unique = true, nullable = false, length = 72)
	public String getEntityUid() {
		return this.entityUid;
	}

	public void setEntityUid(String entityUid) {
		this.entityUid = entityUid;
	}

	@Column(name = "ENTITYVERSION", precision = 10, scale = 0)
	public Long getEntityversion() {
		return this.entityversion;
	}

	public void setEntityversion(Long entityversion) {
		this.entityversion = entityversion;
	}

	@Column(name = "ENTITYSTATE", precision = 10, scale = 0)
	public Long getEntitystate() {
		return this.entitystate;
	}

	public void setEntitystate(Long entitystate) {
		this.entitystate = entitystate;
	}

	@Column(name = "ENEITYCREATOR", length = 100)
	public String getEneitycreator() {
		return this.eneitycreator;
	}

	public void setEneitycreator(String eneitycreator) {
		this.eneitycreator = eneitycreator;
	}

	@Column(name = "ENTITYMODIFIER", length = 100)
	public String getEntitymodifier() {
		return this.entitymodifier;
	}

	public void setEntitymodifier(String entitymodifier) {
		this.entitymodifier = entitymodifier;
	}

	@Column(name = "ENTITYCREATED")
	public Serializable getEntitycreated() {
		return this.entitycreated;
	}

	public void setEntitycreated(Serializable entitycreated) {
		this.entitycreated = entitycreated;
	}

	@Column(name = "ENTITYMODIFIED")
	public Serializable getEntitymodified() {
		return this.entitymodified;
	}

	public void setEntitymodified(Serializable entitymodified) {
		this.entitymodified = entitymodified;
	}

	@Column(name = "PDMCREATOR", length = 510)
	public String getPdmcreator() {
		return this.pdmcreator;
	}

	public void setPdmcreator(String pdmcreator) {
		this.pdmcreator = pdmcreator;
	}

	@Column(name = "PDMMODIFIER", length = 510)
	public String getPdmmodifier() {
		return this.pdmmodifier;
	}

	public void setPdmmodifier(String pdmmodifier) {
		this.pdmmodifier = pdmmodifier;
	}

	@Column(name = "NAME", unique = true, length = 510)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE", length = 510)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "INFO", length = 510)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "APPLIER_NO", length = 510)
	public String getApplierNo() {
		return this.applierNo;
	}

	public void setApplierNo(String applierNo) {
		this.applierNo = applierNo;
	}

	@Column(name = "APPLIER_NAME", length = 510)
	public String getApplierName() {
		return this.applierName;
	}

	public void setApplierName(String applierName) {
		this.applierName = applierName;
	}

	@Column(name = "APPLIER_EMAIL", length = 510)
	public String getApplierEmail() {
		return this.applierEmail;
	}

	public void setApplierEmail(String applierEmail) {
		this.applierEmail = applierEmail;
	}

	@Column(name = "APPLIER_PHONE", length = 510)
	public String getApplierPhone() {
		return this.applierPhone;
	}

	public void setApplierPhone(String applierPhone) {
		this.applierPhone = applierPhone;
	}

	@Column(name = "APPLIER_DPTNO", length = 510)
	public String getApplierDptno() {
		return this.applierDptno;
	}

	public void setApplierDptno(String applierDptno) {
		this.applierDptno = applierDptno;
	}

	@Column(name = "APPLIER_DPTNAME", length = 510)
	public String getApplierDptname() {
		return this.applierDptname;
	}

	public void setApplierDptname(String applierDptname) {
		this.applierDptname = applierDptname;
	}

	@Column(name = "APPLY_DATE")
	public Serializable getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Serializable applyDate) {
		this.applyDate = applyDate;
	}

	@Column(name = "OBJECTBYTES")
	public Blob getObjectbytes() {
		return this.objectbytes;
	}

	public void setObjectbytes(Blob objectbytes) {
		this.objectbytes = objectbytes;
	}

	@Column(name = "PROCESS_INSTANCE_ID", scale = 0)
	public Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	@Column(name = "BUSINESS_STATE", length = 510)
	public String getBusinessState() {
		return this.businessState;
	}

	public void setBusinessState(String businessState) {
		this.businessState = businessState;
	}

	@Column(name = "TASK_INSTANCE_ID", scale = 0)
	public Long getTaskInstanceId() {
		return this.taskInstanceId;
	}

	public void setTaskInstanceId(Long taskInstanceId) {
		this.taskInstanceId = taskInstanceId;
	}

	@Column(name = "TASK_PRIORITY", length = 510)
	public String getTaskPriority() {
		return this.taskPriority;
	}

	public void setTaskPriority(String taskPriority) {
		this.taskPriority = taskPriority;
	}

	@Column(name = "SCHEDULED_START")
	public Serializable getScheduledStart() {
		return this.scheduledStart;
	}

	public void setScheduledStart(Serializable scheduledStart) {
		this.scheduledStart = scheduledStart;
	}

	@Column(name = "SCHEDULED_COMPLETE")
	public Serializable getScheduledComplete() {
		return this.scheduledComplete;
	}

	public void setScheduledComplete(Serializable scheduledComplete) {
		this.scheduledComplete = scheduledComplete;
	}

	@Column(name = "START_")
	public Serializable getStart() {
		return this.start;
	}

	public void setStart(Serializable start) {
		this.start = start;
	}

	@Column(name = "END_")
	public Serializable getEnd() {
		return this.end;
	}

	public void setEnd(Serializable end) {
		this.end = end;
	}

	@Column(name = "PRINCIPAL_ACCOUNT_NAME", length = 510)
	public String getPrincipalAccountName() {
		return this.principalAccountName;
	}

	public void setPrincipalAccountName(String principalAccountName) {
		this.principalAccountName = principalAccountName;
	}

	@Column(name = "PRINCIPAL_PERSON_NAME", length = 510)
	public String getPrincipalPersonName() {
		return this.principalPersonName;
	}

	public void setPrincipalPersonName(String principalPersonName) {
		this.principalPersonName = principalPersonName;
	}

	@Column(name = "PRINCIPAL_EMAIL", length = 510)
	public String getPrincipalEmail() {
		return this.principalEmail;
	}

	public void setPrincipalEmail(String principalEmail) {
		this.principalEmail = principalEmail;
	}

	@Column(name = "PRINCIPAL_EXTENSION", length = 510)
	public String getPrincipalExtension() {
		return this.principalExtension;
	}

	public void setPrincipalExtension(String principalExtension) {
		this.principalExtension = principalExtension;
	}

	@Column(name = "PROJECTTYPE", length = 510)
	public String getProjecttype() {
		return this.projecttype;
	}

	public void setProjecttype(String projecttype) {
		this.projecttype = projecttype;
	}

	@Column(name = "DELAYSTATE", length = 60)
	public String getDelaystate() {
		return this.delaystate;
	}

	public void setDelaystate(String delaystate) {
		this.delaystate = delaystate;
	}

	@Column(name = "ISDELAY", precision = 1, scale = 0)
	public Integer getIsdelay() {
		return this.isdelay;
	}

	public void setIsdelay(Integer isdelay) {
		this.isdelay = isdelay;
	}

	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "FLOW_CHART_VERSION", precision = 10, scale = 0)
	public Long getFlowChartVersion() {
		return this.flowChartVersion;
	}

	public void setFlowChartVersion(Long flowChartVersion) {
		this.flowChartVersion = flowChartVersion;
	}

	@Column(name = "PROJECT_FORM_ID", scale = 0)
	public Long getProjectFormId() {
		return this.projectFormId;
	}

	public void setProjectFormId(Long projectFormId) {
		this.projectFormId = projectFormId;
	}

	@Column(name = "PICTURE_ID", scale = 0)
	public Long getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Long pictureId) {
		this.pictureId = pictureId;
	}

	@Column(name = "FORM_CODE", length = 510)
	public String getFormCode() {
		return this.formCode;
	}

	public void setFormCode(String formCode) {
		this.formCode = formCode;
	}

	@Column(name = "ORIGINAL_NAME", unique = true, length = 510)
	public String getOriginalName() {
		return this.originalName;
	}

	public void setOriginalName(String originalName) {
		this.originalName = originalName;
	}

	@Column(name = "CREATEYEAR", length = 1020)
	public String getCreateyear() {
		return this.createyear;
	}

	public void setCreateyear(String createyear) {
		this.createyear = createyear;
	}

	@Column(name = "PASS_DATE")
	public Serializable getPassDate() {
		return this.passDate;
	}

	public void setPassDate(Serializable passDate) {
		this.passDate = passDate;
	}

	@Column(name = "FORM_KEY", length = 1020)
	public String getFormKey() {
		return this.formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}

	@Column(name = "PDM_CREATOR_PERSON_NAME", length = 1020)
	public String getPdmCreatorPersonName() {
		return this.pdmCreatorPersonName;
	}

	public void setPdmCreatorPersonName(String pdmCreatorPersonName) {
		this.pdmCreatorPersonName = pdmCreatorPersonName;
	}

	@Column(name = "PDM_MODIFIER_PERSON_NAME", length = 1020)
	public String getPdmModifierPersonName() {
		return this.pdmModifierPersonName;
	}

	public void setPdmModifierPersonName(String pdmModifierPersonName) {
		this.pdmModifierPersonName = pdmModifierPersonName;
	}

	@Column(name = "PDM_MODIFIED")
	public Serializable getPdmModified() {
		return this.pdmModified;
	}

	public void setPdmModified(Serializable pdmModified) {
		this.pdmModified = pdmModified;
	}

	@Column(name = "OTHERCODE", length = 1020)
	public String getOthercode() {
		return this.othercode;
	}

	public void setOthercode(String othercode) {
		this.othercode = othercode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set getPhases() {
		return this.phases;
	}

	public void setPhases(Set phases) {
		this.phases = phases;
	}

}
