package com.example.demo.entity;
// Generated 2019/1/19 ���� 08:44:26 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MonitorArea generated by hbm2java
 */
@Entity
@Table(name = "MONITOR_AREA", schema = "SCOTT")
public class MonitorArea implements java.io.Serializable {

	private Long monitorId;
	private String monitorPlay;
	private Long monitorAreaId;
	private String monitorDescription;
	private String monitorNvrIp;
	private String monitorNvrPassword;
	private Integer monitorCh;
	private String monitorNvrUser;
	private String monitorCameraIp;
	private String validFlag;
	
	public MonitorArea() {
	}

	public MonitorArea(Long monitorId) {
		this.monitorId = monitorId;
	}

	public MonitorArea(Long monitorId, String monitorPlay, Long monitorAreaId, String monitorDescription,
			String monitorNvrIp, String monitorNvrPassword, Integer monitorCh, String monitorNvrUser,
			String monitorCameraIp) {
		this.monitorId = monitorId;
		this.monitorPlay = monitorPlay;
		this.monitorAreaId = monitorAreaId;
		this.monitorDescription = monitorDescription;
		this.monitorNvrIp = monitorNvrIp;
		this.monitorNvrPassword = monitorNvrPassword;
		this.monitorCh = monitorCh;
		this.monitorNvrUser = monitorNvrUser;
		this.monitorCameraIp = monitorCameraIp;
	}

	@Id

	@Column(name = "MONITOR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getMonitorId() {
		return this.monitorId;
	}

	public void setMonitorId(Long monitorId) {
		this.monitorId = monitorId;
	}

	@Column(name = "MONITOR_PLAY", length = 200)
	public String getMonitorPlay() {
		return this.monitorPlay;
	}

	public void setMonitorPlay(String monitorPlay) {
		this.monitorPlay = monitorPlay;
	}

	@Column(name = "MONITOR_AREA_ID")
	public Long getMonitorAreaId() {
		return this.monitorAreaId;
	}

	public void setMonitorAreaId(Long monitorAreaId) {
		this.monitorAreaId = monitorAreaId;
	}

	@Column(name = "MONITOR_DESCRIPTION", length = 200)
	public String getMonitorDescription() {
		return this.monitorDescription;
	}

	public void setMonitorDescription(String monitorDescription) {
		this.monitorDescription = monitorDescription;
	}

	@Column(name = "MONITOR_NVR_IP", length = 100)
	public String getMonitorNvrIp() {
		return this.monitorNvrIp;
	}

	public void setMonitorNvrIp(String monitorNvrIp) {
		this.monitorNvrIp = monitorNvrIp;
	}

	@Column(name = "MONITOR_NVR_PASSWORD", length = 100)
	public String getMonitorNvrPassword() {
		return this.monitorNvrPassword;
	}

	public void setMonitorNvrPassword(String monitorNvrPassword) {
		this.monitorNvrPassword = monitorNvrPassword;
	}

	@Column(name = "MONITOR_CH")
	public Integer getMonitorCh() {
		return this.monitorCh;
	}

	public void setMonitorCh(Integer monitorCh) {
		this.monitorCh = monitorCh;
	}

	@Column(name = "MONITOR_NVR_USER", length = 100)
	public String getMonitorNvrUser() {
		return this.monitorNvrUser;
	}

	public void setMonitorNvrUser(String monitorNvrUser) {
		this.monitorNvrUser = monitorNvrUser;
	}

	@Column(name = "MONITOR_CAMERA_IP", length = 100)
	public String getMonitorCameraIp() {
		return this.monitorCameraIp;
	}

	public void setMonitorCameraIp(String monitorCameraIp) {
		this.monitorCameraIp = monitorCameraIp;
	}

	@Column(name = "VALID_FLAG", length = 1)
	public String getValidFlag() {
		return validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}
}
