package com.example.demo.entity;
// Generated 2019/1/18 ���� 05:06:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysMenu generated by hbm2java
 */
@Entity
@Table(name = "SYS_MENU", schema = "SCOTT")
public class SysMenu implements java.io.Serializable {

	private Long menuId;
	private String menuName;
	private String menuHref;
	private Long menuParentId;
	private String menuPermission;
	private String aae100;

	public SysMenu() {
	}

	public SysMenu(Long menuId) {
		this.menuId = menuId;
	}

	public SysMenu(Long menuId, String menuName, String menuHref, Long menuParentId, String menuPermission,
			String aae100) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.menuHref = menuHref;
		this.menuParentId = menuParentId;
		this.menuPermission = menuPermission;
		this.aae100 = aae100;
	}

	@Id

	@Column(name = "MENU_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	@Column(name = "MENU_NAME", length = 50)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "MENU_HREF")
	public String getMenuHref() {
		return this.menuHref;
	}

	public void setMenuHref(String menuHref) {
		this.menuHref = menuHref;
	}

	@Column(name = "MENU_PARENT_ID", precision = 18, scale = 0)
	public Long getMenuParentId() {
		return this.menuParentId;
	}

	public void setMenuParentId(Long menuParentId) {
		this.menuParentId = menuParentId;
	}

	@Column(name = "MENU_PERMISSION", length = 20)
	public String getMenuPermission() {
		return this.menuPermission;
	}

	public void setMenuPermission(String menuPermission) {
		this.menuPermission = menuPermission;
	}

	@Column(name = "AAE100", length = 2)
	public String getAae100() {
		return this.aae100;
	}

	public void setAae100(String aae100) {
		this.aae100 = aae100;
	}

}
