package com.example.demo.entity;
// Generated 2019/1/18 ���� 05:06:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "SYS_ROLE", schema = "SCOTT")
public class SysRole implements java.io.Serializable {

	private Long roleId;
	private String roleName;
	private String roleDescribe;

	public SysRole() {
	}

	public SysRole(Long roleId) {
		this.roleId = roleId;
	}

	public SysRole(Long roleId, String roleName, String roleDescribe) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDescribe = roleDescribe;
	}

	@Id

	@Column(name = "ROLE_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ROLE_NAME", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "ROLE_DESCRIBE", length = 200)
	public String getRoleDescribe() {
		return this.roleDescribe;
	}

	public void setRoleDescribe(String roleDescribe) {
		this.roleDescribe = roleDescribe;
	}

}
