package com.example.demo.entity;
// Generated 2019/1/18 ���� 05:06:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysRoleMenu generated by hbm2java
 */
@Entity
@Table(name = "SYS_ROLE_MENU", schema = "SCOTT")
public class SysRoleMenu implements java.io.Serializable {

	private Long sysRoleMenuId;
	private Long menuId;
	private Long roleId;

	public SysRoleMenu() {
	}

	public SysRoleMenu(Long sysRoleMenuId) {
		this.sysRoleMenuId = sysRoleMenuId;
	}

	public SysRoleMenu(Long sysRoleMenuId, Long menuId, Long roleId) {
		this.sysRoleMenuId = sysRoleMenuId;
		this.menuId = menuId;
		this.roleId = roleId;
	}

	@Id

	@Column(name = "SYS_ROLE_MENU_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getSysRoleMenuId() {
		return this.sysRoleMenuId;
	}

	public void setSysRoleMenuId(Long sysRoleMenuId) {
		this.sysRoleMenuId = sysRoleMenuId;
	}

	@Column(name = "MENU_ID", precision = 18, scale = 0)
	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	@Column(name = "ROLE_ID", precision = 18, scale = 0)
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

}
