package com.example.demo.entity;
// Generated 2019/2/13 ���� 04:55:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemRoleMenu generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_ROLE_MENU", schema = "SCOTT")
public class SystemRoleMenu implements java.io.Serializable {

	private Long id;
	private Long systemRoleId;
	private Long systemMenuId;

	public SystemRoleMenu() {
	}

	public SystemRoleMenu(Long id) {
		this.id = id;
	}

	public SystemRoleMenu(Long id, Long systemRoleId, Long systemMenuId) {
		this.id = id;
		this.systemRoleId = systemRoleId;
		this.systemMenuId = systemMenuId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "SYSTEM_ROLE_ID", precision = 18, scale = 0)
	public Long getSystemRoleId() {
		return this.systemRoleId;
	}

	public void setSystemRoleId(Long systemRoleId) {
		this.systemRoleId = systemRoleId;
	}

	@Column(name = "SYSTEM_MENU_ID", precision = 18, scale = 0)
	public Long getSystemMenuId() {
		return this.systemMenuId;
	}

	public void setSystemMenuId(Long systemMenuId) {
		this.systemMenuId = systemMenuId;
	}

}
