package com.example.demo.entity;
// Generated 2019/2/13 ���� 04:55:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemRole generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_ROLE", schema = "SCOTT")
public class SystemRole implements java.io.Serializable {

	private Long systemRoleId;
	private String systemRoleName;
	private String systemRoleComments;
	private String validStatus;

	public SystemRole() {
	}

	public SystemRole(Long systemRoleId) {
		this.systemRoleId = systemRoleId;
	}

	public SystemRole(Long systemRoleId, String systemRoleName, String systemRoleComments, String validStatus) {
		this.systemRoleId = systemRoleId;
		this.systemRoleName = systemRoleName;
		this.systemRoleComments = systemRoleComments;
		this.validStatus = validStatus;
	}

	@Id

	@Column(name = "SYSTEM_ROLE_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getSystemRoleId() {
		return this.systemRoleId;
	}

	public void setSystemRoleId(Long systemRoleId) {
		this.systemRoleId = systemRoleId;
	}

	@Column(name = "SYSTEM_ROLE_NAME", length = 50)
	public String getSystemRoleName() {
		return this.systemRoleName;
	}

	public void setSystemRoleName(String systemRoleName) {
		this.systemRoleName = systemRoleName;
	}

	@Column(name = "SYSTEM_ROLE_COMMENTS", length = 200)
	public String getSystemRoleComments() {
		return this.systemRoleComments;
	}

	public void setSystemRoleComments(String systemRoleComments) {
		this.systemRoleComments = systemRoleComments;
	}

	@Column(name = "VALID_STATUS", length = 1)
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

}
