package com.example.demo.entity;
// Generated 2019/2/13 ���� 04:55:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_USER", schema = "SCOTT")
public class SystemUser implements java.io.Serializable {

	private Long systemUserId;
	private String userName;
	private String userPassword;

	public SystemUser() {
	}

	public SystemUser(Long systemUserId) {
		this.systemUserId = systemUserId;
	}

	public SystemUser(Long systemUserId, String userName, String userPassword) {
		this.systemUserId = systemUserId;
		this.userName = userName;
		this.userPassword = userPassword;
	}

	@Id

	@Column(name = "SYSTEM_USER_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getSystemUserId() {
		return this.systemUserId;
	}

	public void setSystemUserId(Long systemUserId) {
		this.systemUserId = systemUserId;
	}

	@Column(name = "USER_NAME", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "USER_PASSWORD", length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

}
