package com.example.demo.entity;
// Generated 2019/2/13 ���� 04:55:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemMenu generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_MENU", schema = "SCOTT")
public class SystemMenu implements java.io.Serializable {

	private Long systemMenuId;
	private String systemMenuName;
	private String systemMenuUrl;
	private Long systemMenuOreder;
	private Long systemMenuParentId;
	private String systemMenuComments;
	private String systemMenuIcon;
	private String validStatus;

	public SystemMenu() {
	}

	public SystemMenu(Long systemMenuId) {
		this.systemMenuId = systemMenuId;
	}

	public SystemMenu(Long systemMenuId, String systemMenuName, String systemMenuUrl, Long systemMenuOreder,
			Long systemMenuParentId, String systemMenuComments, String systemMenuIcon, String validStatus) {
		this.systemMenuId = systemMenuId;
		this.systemMenuName = systemMenuName;
		this.systemMenuUrl = systemMenuUrl;
		this.systemMenuOreder = systemMenuOreder;
		this.systemMenuParentId = systemMenuParentId;
		this.systemMenuComments = systemMenuComments;
		this.systemMenuIcon = systemMenuIcon;
		this.validStatus = validStatus;
	}

	@Id

	@Column(name = "SYSTEM_MENU_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getSystemMenuId() {
		return this.systemMenuId;
	}

	public void setSystemMenuId(Long systemMenuId) {
		this.systemMenuId = systemMenuId;
	}

	@Column(name = "SYSTEM_MENU_NAME", length = 200)
	public String getSystemMenuName() {
		return this.systemMenuName;
	}

	public void setSystemMenuName(String systemMenuName) {
		this.systemMenuName = systemMenuName;
	}

	@Column(name = "SYSTEM_MENU_URL", length = 200)
	public String getSystemMenuUrl() {
		return this.systemMenuUrl;
	}

	public void setSystemMenuUrl(String systemMenuUrl) {
		this.systemMenuUrl = systemMenuUrl;
	}

	@Column(name = "SYSTEM_MENU_OREDER", precision = 12, scale = 0)
	public Long getSystemMenuOreder() {
		return this.systemMenuOreder;
	}

	public void setSystemMenuOreder(Long systemMenuOreder) {
		this.systemMenuOreder = systemMenuOreder;
	}

	@Column(name = "SYSTEM_MENU_PARENT_ID", precision = 18, scale = 0)
	public Long getSystemMenuParentId() {
		return this.systemMenuParentId;
	}

	public void setSystemMenuParentId(Long systemMenuParentId) {
		this.systemMenuParentId = systemMenuParentId;
	}

	@Column(name = "SYSTEM_MENU_COMMENTS", length = 200)
	public String getSystemMenuComments() {
		return this.systemMenuComments;
	}

	public void setSystemMenuComments(String systemMenuComments) {
		this.systemMenuComments = systemMenuComments;
	}

	@Column(name = "SYSTEM_MENU_ICON", length = 200)
	public String getSystemMenuIcon() {
		return this.systemMenuIcon;
	}

	public void setSystemMenuIcon(String systemMenuIcon) {
		this.systemMenuIcon = systemMenuIcon;
	}

	@Column(name = "VALID_STATUS", length = 1)
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

}
