package com.example.demo.entity;
// Generated 2019/2/13 ���� 04:55:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemUserRole generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_USER_ROLE", schema = "SCOTT")
public class SystemUserRole implements java.io.Serializable {

	private Long id;
	private Long systemUserId;
	private Long systemRoleId;

	public SystemUserRole() {
	}

	public SystemUserRole(Long id) {
		this.id = id;
	}

	public SystemUserRole(Long id, Long systemUserId, Long systemRoleId) {
		this.id = id;
		this.systemUserId = systemUserId;
		this.systemRoleId = systemRoleId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "SYSTEM_USER_ID", precision = 18, scale = 0)
	public Long getSystemUserId() {
		return this.systemUserId;
	}

	public void setSystemUserId(Long systemUserId) {
		this.systemUserId = systemUserId;
	}

	@Column(name = "SYSTEM_ROLE_ID", precision = 18, scale = 0)
	public Long getSystemRoleId() {
		return this.systemRoleId;
	}

	public void setSystemRoleId(Long systemRoleId) {
		this.systemRoleId = systemRoleId;
	}

}
