package com.example.demo.entity;
// Generated 2019/1/18 ���� 05:06:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysUserRole generated by hbm2java
 */
@Entity
@Table(name = "SYS_USER_ROLE", schema = "SCOTT")
public class SysUserRole implements java.io.Serializable {

	private Long sysUserRoleId;
	private Long userId;
	private Long roleId;

	public SysUserRole() {
	}

	public SysUserRole(Long sysUserRoleId) {
		this.sysUserRoleId = sysUserRoleId;
	}

	public SysUserRole(Long sysUserRoleId, Long userId, Long roleId) {
		this.sysUserRoleId = sysUserRoleId;
		this.userId = userId;
		this.roleId = roleId;
	}

	@Id

	@Column(name = "SYS_USER_ROLE_ID", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getSysUserRoleId() {
		return this.sysUserRoleId;
	}

	public void setSysUserRoleId(Long sysUserRoleId) {
		this.sysUserRoleId = sysUserRoleId;
	}

	@Column(name = "USER_ID", precision = 18, scale = 0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "ROLE_ID", precision = 18, scale = 0)
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

}
